### ISSUE TITLE
 AutoCrew failed during the script generation phase due to a specific error encountered when attempting to process the response from LLM + Log attached

### ISSUE THREAD

**Issue by TerminalGravity** [yanniedog/crewai-autocrew#40]
{logs} [autocrew.log](https://github.com/yanniedog/autocrew/files/14154549/autocrew.log)

### gpt-4 explains:
AutoCrew failed during the script generation phase due to a specific error encountered when attempting to process the response from the Large Language Model (LLM). The core issue that led to the failure was the inability of the AutoCrew system to find and extract CSV data from the LLM's response. This situation is highlighted by the error message "No CSV data found in the response", which was encountered after attempting to generate agent data based on the provided instructions and overall goal.

Here's a breakdown of what happened, why it failed, and how the failure occurred:

### What Happened
- AutoCrew was initialized with the goal of automating the process of creating, formatting, and publishing blog posts by leveraging AI agents and technologies.
- The system started generating alternative scripts based on the user's input, intending to create a crew of AI agents with specific roles, goals, backstories, skills, assigned tasks, and delegation permissions.
- The instruction given to the OpenAI model was to generate a dataset in CSV format containing details for a team of agents working towards the project goal.

### Why It Failed
- The LLM generated a response that, while semantically aligned with the request (providing details such as role, goal, backstory, etc., for a team of agents), did not conform to the expected CSV format. This discrepancy indicates that the model's output was not correctly interpreted or formatted by AutoCrew's processing logic to meet the expected structure for saving as CSV data.
- This failure to extract CSV data suggests either a misunderstanding by the LLM of the format requirement or a processing oversight by AutoCrew in handling the LLM's output.

### How the Failure Occurred
- After receiving the LLM's output, AutoCrew attempted to save this information as CSV data. However, it encountered the error "No CSV data found in the response," indicating that the response did not match the expected format for CSV processing.
- This error prevented AutoCrew from proceeding with the script generation process, leading to the overall failure of the script execution phase.

### Resolution Steps
To address this issue, the AutoCrew system or the user would need to ensure that the instructions to the LLM are clear and explicit about the required CSV format, possibly including more detailed guidance on how the data should be structured. Additionally, enhancing AutoCrew's response processing logic to more flexibly interpret and format LLM outputs into the desired CSV structure could mitigate similar failures in the future.

# My Code+Execution Environment Setup

I used wsl to run autocrew.py from ubuntu terminal.

**Comment by TerminalGravity** [comment]
Here's the raw output from running it using 'wsl' in powershell as admin:

`
Welcome to AutoCrew!
Use the -? or -h command line options to display help information.
Settings can be modified within "config.ini". Scripts are saved in the "scripts" subdirectory.
If you experience any errors, please create an issue on Github and attach "autocrew.log":
https://github.com/yanniedog/autocrew/issues/new

AutoCrew version: 3.1.0
You are running the latest version of AutoCrew.

Generating 2 alternative scripts...

Generating crew 1 of 2 ('alpha' crew)...

Details of your auto-generated crew:

"role","goal","backstory","assigned_task","allow_delegation"
"Lead Developer","Create an Automating Software","With over 10 years of experience in software development","Developing and implementing the software core structure","True"
"UI Designer","Designing the user interface of the Automating Software","Specializes in user interface design, creating seamless experiences","Design user-friendly software interface that allows users to easily navigate","False"
"QA Specialist","Ensure the Automating Software is working perfectly","Experienced tester who has an eye for detail","Testing the software, identifying bugs, & reporting back to the team","True"
"Database Admin","Ensuring the smooth running of the database","Has in-depth knowledge of database operations","Overseeing the efficiency of the server and the security of the database","False"
"Business Analyst","Understand the business needs","Skilled in translating business needs into technical requirements","Gathering, understanding, and documenting business requirements","True"
"Solution Architect","Design the structure of the system","Has solid experience in designing robust, scalable systems","Designing scalable, reliable, and performant systems","False"

Your CrewAI script is saved here: scripts/crewai-autocrew-20240203-164948-automate-the-process-of-creating,-format-alpha.py

Generating crew 2 of 2 ('beta' crew)...
No CSV data found in the response.
Failed to process LLM response: No CSV data found in the response
An error occurred during script generation.
Traceback (most recent call last):
  File "/home/jack/repositories/autocrew/autocrew.py", line 286, in generate_and_run_scripts
    csv_file_paths = autocrew.generate_scripts(truncated_overall_goal, num_scripts_to_generate)
  File "/home/jack/repositories/autocrew/core.py", line 210, in generate_scripts
    file_path = self.generate_single_script(i, num_scripts, overall_goal, crew_name)
  File "/home/jack/repositories/autocrew/core.py", line 258, in generate_single_script
    return process_response(response)
  File "/home/jack/repositories/autocrew/core.py", line 221, in process_response
    file_path = save_csv_output(response, overall_goal, truncation_length=self.overall_goal_truncation_for_filenames, greek_suffix=greek_suffix)
  File "/home/jack/repositories/autocrew/utils.py", line 140, in save_csv_output
    raise ValueError("No CSV data found in the response")
ValueError: No CSV data found in the response
Autocrew script returned a non-zero exit code.
Autocrew script execution failed.
jack in autocrew on  main [!] took 31.9s
❯
`
