### ISSUE TITLE
Autocrew+Ollama failures

### ISSUE THREAD

**Issue by andr6** [yanniedog/crewai-autocrew#48]
Errors when finishing to execute autocrew :

> 2024-02-22 15:01:52,205 - [DEBUG] [utils.py:save_csv_output:156] CSV file saved at: /opt/autocrew/scripts/crewai-autocrew-20240222-150152-given-a-step-of-debian-type-linux-messag-alpha.csv
2024-02-22 15:01:52,205 - [ERROR] [utils.py:parse_csv_data:68] CSV data not found in the response.
2024-02-22 15:01:52,211 - [DEBUG] [welcome.py:run_autocrew_script:116] CSV data not found in the response.
2024-02-22 15:01:52,217 - [ERROR] [core.py:generate_single_script:260] Failed to process LLM response: CSV data not found in the response
2024-02-22 15:01:52,217 - [DEBUG] [welcome.py:run_autocrew_script:116] Failed to process LLM response: CSV data not found in the response
2024-02-22 15:01:52,218 - [ERROR] [autocrew.py:generate_and_run_scripts:293] An error occurred during script generation.
Traceback (most recent call last):
  File "/opt/autocrew/autocrew.py", line 286, in generate_and_run_scripts
    csv_file_paths = autocrew.generate_scripts(truncated_overall_goal, num_scripts_to_generate)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/autocrew/core.py", line 210, in generate_scripts
    file_path = self.generate_single_script(i, num_scripts, overall_goal, crew_name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/autocrew/core.py", line 258, in generate_single_script
    return process_response(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/autocrew/core.py", line 222, in process_response
    agents_data = parse_csv_data(response, delimiter=',', filename=file_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/autocrew/utils.py", line 69, in parse_csv_data
    raise ValueError('CSV data not found in the response')
ValueError: CSV data not found in the response
2024-02-22 15:01:52,220 - [DEBUG] [welcome.py:run_autocrew_script:116] An error occurred during script generation.
2024-02-22 15:01:52,220 - [DEBUG] [welcome.py:run_autocrew_script:116] Traceback (most recent call last):
2024-02-22 15:01:52,220 - [DEBUG] [welcome.py:run_autocrew_script:116] File "/opt/autocrew/autocrew.py", line 286, in generate_and_run_scripts
2024-02-22 15:01:52,220 - [DEBUG] [welcome.py:run_autocrew_script:116] csv_file_paths = autocrew.generate_scripts(truncated_overall_goal, num_scripts_to_generate)
2024-02-22 15:01:52,220 - [DEBUG] [welcome.py:run_autocrew_script:116] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-22 15:01:52,221 - [DEBUG] [welcome.py:run_autocrew_script:116] File "/opt/autocrew/core.py", line 210, in generate_scripts
2024-02-22 15:01:52,221 - [DEBUG] [welcome.py:run_autocrew_script:116] file_path = self.generate_single_script(i, num_scripts, overall_goal, crew_name)
2024-02-22 15:01:52,221 - [DEBUG] [welcome.py:run_autocrew_script:116] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-22 15:01:52,221 - [DEBUG] [welcome.py:run_autocrew_script:116] File "/opt/autocrew/core.py", line 258, in generate_single_script
2024-02-22 15:01:52,221 - [DEBUG] [welcome.py:run_autocrew_script:116] return process_response(response)
2024-02-22 15:01:52,221 - [DEBUG] [welcome.py:run_autocrew_script:116] ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-22 15:01:52,221 - [DEBUG] [welcome.py:run_autocrew_script:116] File "/opt/autocrew/core.py", line 222, in process_response
2024-02-22 15:01:52,222 - [DEBUG] [welcome.py:run_autocrew_script:116] agents_data = parse_csv_data(response, delimiter=',', filename=file_path)
2024-02-22 15:01:52,222 - [DEBUG] [welcome.py:run_autocrew_script:116] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-02-22 15:01:52,222 - [DEBUG] [welcome.py:run_autocrew_script:116] File "/opt/autocrew/utils.py", line 69, in parse_csv_data
2024-02-22 15:01:52,222 - [DEBUG] [welcome.py:run_autocrew_script:116] raise ValueError('CSV data not found in the response')
2024-02-22 15:01:52,222 - [DEBUG] [welcome.py:run_autocrew_script:116] ValueError: CSV data not found in the response
2024-02-22 15:01:53,237 - [ERROR] [welcome.py:run_autocrew_script:122] Autocrew script returned a non-zero exit code.
2024-02-22 15:01:53,237 - [ERROR] [welcome.py:main:374] Autocrew script execution failed.

**Comment by theCyberTech** [comment]
issue has been identified - Fix currently being worked on
