### ISSUE TITLE
ValueError: No CSV data found in the response

### ISSUE THREAD

**Issue by slavakurilyak** [yanniedog/crewai-autocrew#49]
Running `python autocrew.py` gives me:

Here's my stack trace:

```sh
Welcome to AutoCrew!
Use the -? or -h command line options to display help information.
Settings can be modified within "config.ini". Scripts are saved in the "scripts" subdirectory.
If you experience any errors, please create an issue on Github and attach "autocrew.log":
https://github.com/yanniedog/autocrew/issues/new

AutoCrew version: 3.1.0
You are running the latest version of AutoCrew.

Generating 3 alternative scripts...

Generating crew 1 of 3 ('alpha' crew)...
No CSV data found in the response.
Failed to process LLM response: No CSV data found in the response
An error occurred during script generation.
Traceback (most recent call last):
  File "/Users/slava/dev/testing/Autocrew/autocrew.py", line 286, in generate_and_run_scripts
    csv_file_paths = autocrew.generate_scripts(truncated_overall_goal, num_scripts_to_generate)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/dev/testing/Autocrew/core.py", line 210, in generate_scripts
    file_path = self.generate_single_script(i, num_scripts, overall_goal, crew_name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/dev/testing/Autocrew/core.py", line 258, in generate_single_script
    return process_response(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/dev/testing/Autocrew/core.py", line 221, in process_response
    file_path = save_csv_output(response, overall_goal, truncation_length=self.overall_goal_truncation_for_filenames, greek_suffix=greek_suffix)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/slava/dev/testing/Autocrew/utils.py", line 140, in save_csv_output
    raise ValueError("No CSV data found in the response")
ValueError: No CSV data found in the response
Autocrew script returned a non-zero exit code.
Autocrew script execution failed.
```

Any ideas?

**Comment by yanniedog** [comment]
Could you please upload the autocrew.log file? Each time Autocrew runs, a new log file is saved. The log file provides important debug info which will be very helpful. Looking forward to hearing back from you

**Comment by slavakurilyak** [comment]
Didn't realize you setup logging

I figured out the issue and opened a pull request for the fix
